import type {
  ProfessionalRequirement,
  PropertySector,
  RecurrenceType,
  TaskPriority,
  TaskType,
} from '../types/enums';

export interface TaskTemplateSeed {
  name: string;
  taskType: TaskType;
  professionalRequirement: ProfessionalRequirement;
  technicalDescription?: string;
  priority: TaskPriority;
  recurrenceType: RecurrenceType;
  recurrenceMonths: number;
  estimatedDurationMinutes?: number;
  defaultSector: PropertySector;
}

export interface CategoryTemplateSeed {
  name: string;
  icon: string;
  description: string;
  displayOrder: number;
  tasks: TaskTemplateSeed[];
}

export const TEMPLATE_SEED_DATA: CategoryTemplateSeed[] = [
  {
    name: 'Estructura',
    icon: '🏗',
    description: 'Control estructural de la vivienda',
    displayOrder: 0,
    tasks: [
      {
        name: 'Inspección visual de vigas y columnas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar visualmente vigas y columnas en busca de fisuras, deformaciones o manchas de humedad. Verificar que no haya desprendimientos de material.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control de fisuras en muros',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Examinar muros interiores y exteriores buscando fisuras nuevas o crecimiento de existentes. Marcar con cinta y fotografiar para seguimiento.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 45,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Evaluación profesional de fundaciones',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Evaluación técnica de cimientos y fundaciones por profesional matriculado. Incluye nivel de asentamientos y estado general.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 120,
        defaultSector: 'BASEMENT',
      },
      {
        name: 'Verificación de juntas de dilatación',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Inspeccionar el estado de las juntas de dilatación en losas y muros. Verificar sellado y flexibilidad del material.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Reparación de fisuras detectadas',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Reparar fisuras detectadas en inspecciones previas. Aplicar sellador o mortero según corresponda al tipo de fisura.',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control de humedad ascendente en cimientos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Inspeccionar base de muros y zócalos buscando manchas de humedad ascendente por capilaridad. Verificar estado de capa aisladora.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'BASEMENT',
      },
      {
        name: 'Evaluación estructural integral quinquenal',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Evaluación completa del estado estructural por ingeniero matriculado. Incluye fundaciones, losas, vigas, columnas y muros portantes.',
        priority: 'HIGH',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 60,
        estimatedDurationMinutes: 240,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Inspección de losa de hormigón armado',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Revisar losas macizas o de viguetas pretensadas buscando fisuras de flexión, retracción o armaduras expuestas/oxidadas. Verificar desprendimientos de recubrimiento.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de revoques exteriores',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar adherencia del revoque golpeando con nudillos (sonido hueco indica desprendimiento). Buscar fisuras mapa, ampollas y desprendimientos en muros de ladrillo hueco con revoque cementicio.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Inspección de muros portantes de mampostería',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar aplomo de muros, buscar fisuras diagonales (indican asentamientos diferenciales), evaluar estado de juntas de mortero. Específico de construcción con ladrillo común o hueco.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 60,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Techos y Cubiertas',
    icon: '🏠',
    description: 'Mantenimiento de techos, membranas y desagües pluviales',
    displayOrder: 1,
    tasks: [
      {
        name: 'Inspección de membrana hidrófuga',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar estado de la membrana asfáltica o hidrófuga en techos planos. Buscar burbujas, grietas o despegues en uniones.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 40,
        defaultSector: 'ROOF',
      },
      {
        name: 'Limpieza de canaletas y bajadas pluviales',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Limpiar hojas, tierra y sedimentos de canaletas y verificar libre circulación de bajadas pluviales. Probar con agua.',
        priority: 'HIGH',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 45,
        defaultSector: 'ROOF',
      },
      {
        name: 'Control de tejas o chapa',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de tejas (rotas, desplazadas) o chapas (oxidación, tornillos flojos). Controlar sellado en cumbrera.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'ROOF',
      },
      {
        name: 'Tratamiento impermeabilizante',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Aplicar tratamiento impermeabilizante en terraza o techo plano. Incluye limpieza previa y aplicación de producto protector.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 180,
        defaultSector: 'ROOF',
      },
      {
        name: 'Reparación de filtraciones',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Detectar y reparar filtraciones activas en techos. Requiere identificación del punto de ingreso y sellado profesional.',
        priority: 'URGENT',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'ROOF',
      },
      {
        name: 'Reemplazo integral de membrana asfáltica',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Reemplazo completo de membrana asfáltica en techos planos. Incluye retiro de membrana vieja, preparación de superficie y colocación nueva.',
        priority: 'HIGH',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 120,
        estimatedDurationMinutes: 480,
        defaultSector: 'ROOF',
      },
      {
        name: 'Inspección post-granizo',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Tras tormentas de granizo: verificar daños en membrana, tejas rotas, chapas abolladas, canaletas dañadas. Documentar con fotos para reclamo de seguro.',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 40,
        defaultSector: 'ROOF',
      },
      {
        name: 'Control de claraboyas y lucernarios',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar sellado perimetral, estado de policarbonato o vidrio, bisagras si es abatible. Las juntas se resecan con el calor y pierden hermeticidad.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'ROOF',
      },
      {
        name: 'Limpieza de techos y terrazas',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Barrer hojas, tierra acumulada y vegetación parasitaria (musgos, líquenes). La acumulación retiene humedad y deteriora membranas. Especialmente en clima húmedo del Litoral.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 45,
        defaultSector: 'ROOF',
      },
      {
        name: 'Revisión de babetas y encuentros',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar sellado en babetas (unión de pared con techo), encuentros con chimeneas, conductos de ventilación y antenas. Son puntos críticos de filtración.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'ROOF',
      },
    ],
  },
  {
    name: 'Instalación Eléctrica',
    icon: '⚡',
    description: 'Seguridad eléctrica, tablero y protecciones',
    displayOrder: 2,
    tasks: [
      {
        name: 'Prueba de disyuntor diferencial (ID)',
        taskType: 'TEST',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Presionar botón de test del interruptor diferencial. Debe cortar el suministro inmediatamente. Si no corta, llamar a electricista.',
        priority: 'URGENT',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 5,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de tablero eléctrico',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Revisar estado del tablero: térmicas, conexiones, cables sueltos, signos de recalentamiento. Verificar identificación de circuitos.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Medición de puesta a tierra',
        taskType: 'MEASUREMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Medir resistencia de puesta a tierra con telurímetro. Valor debe ser menor a 10 ohms según reglamentación AEA.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de tomacorrientes y llaves',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que todos los tomacorrientes y llaves de luz funcionen correctamente. Buscar signos de chispas, calor o decoloración.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Revisión de instalación eléctrica completa',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Revisión completa de la instalación eléctrica por electricista matriculado. Incluye termografía y mediciones de aislación.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 36,
        estimatedDurationMinutes: 240,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Medición de aislación de conductores (megado)',
        taskType: 'MEASUREMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Medir resistencia de aislación con megóhmetro en circuitos principales. Cables envejecidos con aislación reseca son riesgo de incendio. Norma AEA 90364.',
        priority: 'HIGH',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 36,
        estimatedDurationMinutes: 60,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de protecciones térmicas por circuito',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar que cada térmica proteja un circuito individual. Verificar calibre correcto según sección de cable. Norma AEA 90364.',
        priority: 'HIGH',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 36,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de medidor eléctrico y acometida',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Inspeccionar estado del medidor, cables de acometida, caja de toma. Verificar que el precinto esté intacto. Reportar anomalías a la distribuidora.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de protección contra sobretensiones (DPS)',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Controlar si existe dispositivo de protección contra sobretensiones en tablero. Fundamental en zonas con tormentas eléctricas frecuentes. Norma AEA 90364-4-443.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de instalación eléctrica enterrada',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Si existe canalización subterránea: verificar estado de caños, cámaras de inspección, sellados. Buscar ingreso de agua o raíces.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Instalación Sanitaria',
    icon: '🚿',
    description: 'Plomería, desagües y agua corriente',
    displayOrder: 3,
    tasks: [
      {
        name: 'Inspección de canillas y griferías',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que no haya goteos en canillas de cocina, baños y lavadero. Revisar estado de las juntas y aireadores.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 20,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Limpieza de sifones y rejillas',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Desarmar y limpiar sifones de piletas. Retirar residuos de rejillas de piso. Verificar buen escurrimiento del agua.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 30,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Control de tanque de agua',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Inspeccionar tanque de reserva: nivel de agua, estado de flotante, tapa bien colocada, limpieza interna si corresponde.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'TERRACE',
      },
      {
        name: 'Limpieza y desinfección de tanque',
        taskType: 'CLEANING',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Vaciar tanque, cepillar paredes interiores, enjuagar y desinfectar con lavandina diluida. Dejar secar antes de llenar.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'TERRACE',
      },
      {
        name: 'Detección de pérdidas ocultas',
        taskType: 'TEST',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Cerrar todas las canillas, verificar que el medidor de agua no siga girando. Si gira, hay una pérdida oculta. Llamar a plomero.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de termotanque y ánodo de sacrificio',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Inspeccionar estado del termotanque: verificar ánodo de sacrificio, válvula de seguridad, conexiones y ausencia de pérdidas. Reemplazar ánodo si está consumido.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Mantenimiento de cámara séptica',
        taskType: 'CLEANING',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Vaciado y limpieza de cámara séptica por servicio atmosférico. Verificar estado de paredes y tapa. Aplicable a viviendas sin red cloacal.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 120,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Inspección de llave de paso general de agua',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que la llave de paso general de agua funcione correctamente (apertura y cierre total). Lubricar si es de bronce. Fundamental para cortar el agua en emergencias.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de bomba presurizadora',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar funcionamiento automático, presión de trabajo, ruidos anormales, pérdidas en conexiones. Limpiar filtro de succión. Revisar membrana del tanque hidroneumático.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de cañerías visibles',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar cañerías expuestas (calefón, bajo mesada, lavadero): buscar corrosión en caño galvanizado, fisuras en termofusión, manchas de humedad en juntas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Limpieza de pozo de bombeo',
        taskType: 'CLEANING',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Vaciado y limpieza por servicio atmosférico. Verificar funcionamiento de bomba sumergible si tiene. Común en viviendas sin red cloacal completa.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de válvula de retención',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Controlar que la válvula de retención (check) evite el retorno de agua en la bomba o tanque de reserva. Si no retiene, la bomba cicla continuamente.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Gas y Calefacción',
    icon: '🔥',
    description: 'Instalación de gas, calefacción y agua caliente',
    displayOrder: 4,
    tasks: [
      {
        name: 'Revisión de artefactos de gas',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificación de funcionamiento seguro de calefones, estufas, hornos y calefactores. Control de combustión y ventilación.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de llama piloto y quemadores',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que la llama de quemadores sea azul y estable. Llama amarilla o irregular indica mala combustión. Ventilar y llamar gasista.',
        priority: 'HIGH',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Prueba de monóxido de carbono',
        taskType: 'TEST',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Medición de niveles de CO con detector certificado en ambientes con artefactos de gas. Verificar ventilaciones y tirajes.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Limpieza de conductos de ventilación',
        taskType: 'CLEANING',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Limpiar rejillas de ventilación y verificar que los conductos de tiraje estén libres de obstrucciones.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Service de caldera/calefón',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Servicio técnico completo del calefón o caldera: limpieza de intercambiador, revisión de válvulas, ajuste de presión.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 90,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Revisión periódica obligatoria NAG-226',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Inspección obligatoria de toda la instalación de gas según norma NAG-226. Incluye prueba de hermeticidad de cañerías, verificación de llaves, reguladores y conexiones. Debe ser realizada por gasista matriculado.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 90,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de llave de paso general de gas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que la llave de paso general (antes del medidor) funcione correctamente. Debe girar sin dificultad. Identificar su ubicación y asegurar acceso libre.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 5,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control del medidor de gas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Inspeccionar estado del medidor: corrosión, golpes, pérdidas audibles (silbido). Verificar que el registro sea accesible para lectura de la distribuidora.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de chimenea y conducto de humos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar que el conducto de humos (de calefón, caldera o estufa tiro balanceado) esté libre de obstrucciones, sellado en sus uniones, y con sombrerete en buen estado. Riesgo de CO.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Aberturas',
    icon: '🚪',
    description: 'Puertas, ventanas, cerraduras y herrajes',
    displayOrder: 5,
    tasks: [
      {
        name: 'Lubricación de bisagras y cerraduras',
        taskType: 'LUBRICATION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Aplicar lubricante en aerosol o grafito en todas las bisagras de puertas y cerraduras. Verificar libre movimiento.',
        priority: 'LOW',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Ajuste de burletes y sellados',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar y reemplazar burletes deteriorados en ventanas y puertas exteriores. Controlar sellado perimetral.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección de marcos y premarcos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de marcos de madera (humedad, hongos), aluminio (oxidación) o PVC (deformación). Buscar separaciones del muro.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de vidrios y masillas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar vidrios en busca de rajaduras y verificar estado de masillas o selladores. Reemplazar los deteriorados.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Tratamiento de marcos de madera',
        taskType: 'TREATMENT',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Aplicar protector, barniz o pintura a marcos de madera expuestos a intemperie. Lijar previamente si hay descascaramiento.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 120,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Mantenimiento de persianas de enrollar',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar funcionamiento de la cinta o cadena, estado de tablillas, lubricación del eje. Limpiar guías laterales. Muy común en viviendas argentinas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de mosquiteros',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de la tela mosquitera (roturas, despegues del marco). Fundamental en zona Litoral por presencia de mosquitos (dengue).',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección de rejas y protecciones metálicas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar soldaduras, fijación a muros, estado de pintura o galvanizado. Buscar corrosión, especialmente en bases empotradas. Incluye portones y barandas metálicas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 25,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Pintura y Revestimientos',
    icon: '🎨',
    description: 'Pintura interior/exterior, revoques y revestimientos',
    displayOrder: 6,
    tasks: [
      {
        name: 'Inspección de pintura exterior',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar fachadas y muros exteriores: descascaramiento, ampollas, manchas de humedad, hongos o eflorescencias.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control de humedad en muros interiores',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Buscar manchas de humedad, moho o desprendimiento de pintura en paredes interiores, especialmente en baños y cocina.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Tratamiento anti-humedad',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Aplicar tratamiento hidrófugo o anti-humedad en zonas afectadas. Incluye preparación de superficie y aplicación de producto.',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección de revestimientos cerámicos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar adhesión de cerámicos en baños y cocina golpeando suavemente. Sonido hueco indica despegue. Revisar juntas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Sellado de juntas en áreas húmedas',
        taskType: 'SEALING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Renovar sellado de silicona en uniones de bañera, ducha, piletas y mesadas. Remover silicona vieja antes de aplicar nueva.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Repintado de fachada exterior',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Repintado completo de muros exteriores con pintura para exteriores. Incluye reparación de revoques dañados, enduido y dos manos de pintura. Protege el revoque.',
        priority: 'MEDIUM',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 48,
        estimatedDurationMinutes: 480,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Tratamiento de capa aisladora horizontal',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Si hay humedad ascendente crónica: evaluar estado de la capa aisladora horizontal. Puede requerir inyección de silicona hidrófuga en base de muros.',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 240,
        defaultSector: 'BASEMENT',
      },
      {
        name: 'Inspección de revoques interiores',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar adherencia de revoques interiores golpeando con nudillos (sonido hueco indica desprendimiento). Buscar fisuras, ampollas. Los revoques a la cal son más susceptibles.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 25,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Jardín y Exteriores',
    icon: '🌳',
    description: 'Espacios exteriores, veredas, medianeras y jardín',
    displayOrder: 7,
    tasks: [
      {
        name: 'Inspección de veredas y senderos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar estado de veredas y senderos: baldosas flojas, grietas, desniveles peligrosos, crecimiento de raíces.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 20,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Control de medianeras y cercos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Inspeccionar medianeras: fisuras, inclinación, humedad. Verificar estado de cercos perimetrales y portones.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Limpieza de desagües exteriores',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Limpiar rejillas de desagüe pluvial, cunetas y canaletas exteriores. Verificar pendiente correcta hacia desagüe.',
        priority: 'HIGH',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Control de pileta de natación',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado del vaso, revestimiento, equipos de filtrado y niveles de químicos. Inspeccionar bordes y coping.',
        priority: 'MEDIUM',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Poda de árboles cercanos a la estructura',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Podar ramas que estén en contacto o próximas a techos, cables o canaletas. Previene daños por tormentas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Mantenimiento de parrilla y quincho',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar estado del hogar: fisuras en ladrillos refractarios, estado de la rejilla y asador, limpieza del conducto de humos, revoque de chimenea.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Control de cochera y garaje',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de losa o techo, piso (fisuras, manchas de aceite), portón (mecanismo, rieles, motor si es automático), iluminación, instalación eléctrica.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Inspección de pérgola, semi-cubierta o deck',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de la madera o metal: buscar pudrición, termitas, oxidación. Aplicar protector o lasur a madera. Controlar fijaciones y tornillería.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Mantenimiento de sistema de riego',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar aspersores, goteros, electroválvulas, timer/programador. Purgar sistema antes del invierno para evitar daños por heladas.',
        priority: 'LOW',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Inspección de cerco perimetral y portones',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de alambrados, tejidos, cercos vivos, postes. Portones: herrajes, soldaduras, motor automático, fotoceldas de seguridad.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 25,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Control de tanque cisterna enterrado',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar hermeticidad, estado de bomba, flotante, tapa. Limpiar y desinfectar. Común en zonas con baja presión de red de agua.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Inspección de muro de contención',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Si la propiedad tiene desniveles: verificar estado del muro de contención, barbacanas de drenaje, fisuras, inclinación. Detectar movimientos.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Puesta en marcha y cierre estacional de pileta',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Apertura: destapar, limpiar, poner en marcha filtro, tratar agua. Cierre: bajar pH, agregar alguicida, tapar. Específico del clima estacional argentino.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 60,
        defaultSector: 'GARDEN',
      },
    ],
  },
  {
    name: 'Climatización',
    icon: '❄️',
    description: 'Aire acondicionado, ventilación y confort térmico',
    displayOrder: 8,
    tasks: [
      {
        name: 'Limpieza de filtros de aire acondicionado',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Retirar y lavar filtros de cada split con agua y jabón neutro. Dejar secar completamente antes de reinstalar.',
        priority: 'HIGH',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Service de aire acondicionado',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Servicio técnico completo: limpieza de evaporador y condensador, verificación de gas refrigerante, control eléctrico.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 90,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de unidad exterior',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que la unidad exterior no tenga obstrucciones, que las aletas no estén dobladas y que drene correctamente.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de ventilación natural',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que las rejillas de ventilación natural estén libres de obstrucciones. Son obligatorias en ambientes con gas.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 10,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Evaluación de aislación térmica',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Evaluación del estado de aislación térmica en techos y muros. Identificar puentes térmicos y recomendar mejoras.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 36,
        estimatedDurationMinutes: 120,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección de calefacción por losa radiante',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar presión del circuito, purgar aire de radiadores/circuitos, controlar caldera asociada. Aplica a viviendas con piso radiante.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de ventiladores de techo',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar fijación al cielorraso (especialmente en durlock), balanceo, ruidos, funcionamiento de velocidades y reversa.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Humedad e Impermeabilización',
    icon: '💧',
    description: 'Control de humedad, impermeabilización y aislación hidrófuga',
    displayOrder: 9,
    tasks: [
      {
        name: 'Inspección de manchas y eflorescencias',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Recorrer muros interiores y exteriores buscando manchas de humedad, eflorescencias (sales blancas) y desprendimientos de pintura que indiquen infiltración.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'BASEMENT',
      },
      {
        name: 'Control de muros enterrados y subsuelos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Inspeccionar muros de sótano o semi-enterrados. Verificar estado de impermeabilización exterior y presencia de filtraciones. Medir humedad con higrómetro.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'BASEMENT',
      },
      {
        name: 'Verificación de impermeabilización en baños y cocina',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de sellados en encuentros piso-pared de duchas, bañeras y mesadas. Buscar signos de filtración en techos inferiores.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Control de ventilación para prevención de condensación',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar correcto funcionamiento de extractores y ventilación natural en baños, cocina y lavadero. La condensación crónica genera moho y deterioro.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección post-lluvia intensa',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Tras lluvias fuertes: recorrer la vivienda buscando filtraciones activas, goteras, acumulación de agua en terraza. Documentar para seguimiento. Frecuente en Litoral nov-mar.',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control de drenaje perimetral',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar que el drenaje perimetral de la vivienda funcione correctamente. Buscar empozamientos contra muros. Limpiar caños de drenaje. Crítico en zona Litoral con napa freática alta.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'GARDEN',
      },
    ],
  },
  {
    name: 'Seguridad contra Incendio',
    icon: '🧯',
    description: 'Detección de humo, matafuegos y prevención de incendios',
    displayOrder: 10,
    tasks: [
      {
        name: 'Verificación de detectores de humo',
        taskType: 'TEST',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Presionar botón de test de cada detector de humo. Verificar que suene la alarma. Reemplazar baterías si no funciona. IRAM 3517 recomienda uno por nivel mínimo.',
        priority: 'HIGH',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 10,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control y recarga de matafuegos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar presión del manómetro, estado de la manguera, precinto y fecha de vencimiento. Recargar o reemplazar si corresponde. Mínimo 1 matafuego ABC por planta.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Revisión de instalación eléctrica como fuente de ignición',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar que no haya cables pelados, empalmes sin aislar, tableros con signos de recalentamiento u otros riesgos eléctricos que puedan causar incendio.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de vías de evacuación',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Asegurar que pasillos, escaleras y salidas no estén obstruidos. Verificar que las puertas de salida abran correctamente. Identificar punto de reunión familiar.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 15,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de detector de monóxido de carbono',
        taskType: 'TEST',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar funcionamiento del detector de CO (botón test). Cambiar baterías. Verificar fecha de vencimiento del sensor (5-7 años). Obligatorio según NAG-200 en ambientes con gas.',
        priority: 'HIGH',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 5,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Revisión de instalación de gas como fuente de ignición',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar que no haya pérdidas de gas en conexiones flexibles, llaves, y que los artefactos tengan válvula de seguridad (corte por ausencia de llama).',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Control de Plagas',
    icon: '🐛',
    description: 'Prevención y control de plagas urbanas',
    displayOrder: 11,
    tasks: [
      {
        name: 'Inspección general de indicios de plagas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Recorrer la vivienda buscando indicios de plagas: excrementos, roeduras, nidos, senderos de hormigas, telas de araña excesivas, cucarachas.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control preventivo de termitas',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Inspeccionar marcos de madera, muebles empotrados, estructuras de techo y zócalos buscando túneles de barro, madera hueca o alas descartadas de termitas.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Desinsectación preventiva',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Aplicación profesional de insecticida en perímetro, cañerías, bajo mesadas y puntos críticos. Productos aprobados por ANMAT.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 90,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Desratización preventiva',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Colocación de estaciones de cebo y sellado de posibles ingresos. Verificar que no haya fuentes de alimento accesibles para roedores.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 60,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Eliminación de criaderos de mosquitos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Eliminar recipientes con agua estancada: cubiertas, platos de macetas, baldes, canaletas obstruidas. Aplicar larvicida en desagües. Crítico para prevención de dengue en Litoral.',
        priority: 'HIGH',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 20,
        defaultSector: 'EXTERIOR',
      },
      {
        name: 'Control de murciélagos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar si hay colonia de murciélagos en entretechos, aleros o persianas. No eliminar (especie protegida) pero sellar accesos con exclusión. Riesgo de rabia.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'EXTERIOR',
      },
    ],
  },
  {
    name: 'Pisos y Contrapisos',
    icon: '🧱',
    description: 'Estado de pisos, contrapisos, juntas y nivelación',
    displayOrder: 12,
    tasks: [
      {
        name: 'Inspección general de pisos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Recorrer todos los ambientes verificando baldosas flojas (golpear suavemente), desniveles, fisuras en pisos de cemento y desgaste excesivo.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Verificación de contrapiso y nivelación',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar que no haya hundimientos o levantamientos en el contrapiso. Controlar pendientes hacia desagües en áreas húmedas.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 45,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Sellado de juntas de dilatación en pisos',
        taskType: 'SEALING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Inspeccionar y renovar sellador en juntas de dilatación de pisos. Evitar ingreso de agua y acumulación de suciedad.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 45,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Tratamiento de pisos de madera o parquet',
        taskType: 'TREATMENT',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Lijar y plastificar cuando el desgaste lo requiera. Reparar tablas sueltas. Verificar que no haya humedad debajo (contrapiso).',
        priority: 'MEDIUM',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 48,
        estimatedDurationMinutes: 480,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Limpieza y sellado de pisos de piedra natural',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Limpiar con producto específico. Aplicar sellador en piedras naturales (mármol, granito, travertino) para evitar manchas y deterioro.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Mobiliario y Equipamiento Fijo',
    icon: '🪑',
    description:
      'Inspección de muebles fijos, mesadas, sanitarios y artefactos integrados a la vivienda',
    displayOrder: 13,
    tasks: [
      {
        name: 'Inspección de alacenas y bajo-mesadas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar bisagras, estantes, fondo de muebles en busca de humedad, hinchazón de melamina o signos de termitas. Verificar que las puertas cierren correctamente.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'KITCHEN',
      },
      {
        name: 'Inspección de mesada y bacha',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar sellado de la mesada contra la pared (silicona o junta). Revisar estado de la bacha, desagüe y griferías. Buscar manchas de humedad debajo.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'KITCHEN',
      },
      {
        name: 'Limpieza de filtros de extractor de cocina',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Retirar filtros de grasa del extractor/campana, lavar con desengrasante, secar y reinstalar. Verificar que el motor funcione correctamente.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 20,
        defaultSector: 'KITCHEN',
      },
      {
        name: 'Inspección de campana extractora',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar estado del motor, ducto de salida al exterior, conexión eléctrica y fijación a pared. Verificar que la extracción sea efectiva (prueba con papel).',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'KITCHEN',
      },
      {
        name: 'Inspección de mueble de baño/vanitory',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar estado del mueble: humedad, hinchazón, bisagras, sellado contra pared. Verificar que no haya pérdidas en las conexiones debajo del lavatorio.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Control de mecanismo de descarga de inodoro',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar funcionamiento del botón/palanca de descarga. Escuchar si el agua sigue corriendo después de la descarga (indica pérdida en la válvula). Revisar flotante.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 10,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Verificación de fijación de sanitarios',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar que inodoro y bidet estén firmes al piso (sin movimiento). Revisar sellado de la base con silicona. Buscar signos de pérdida de agua alrededor.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 10,
        defaultSector: 'BATHROOM',
      },
      {
        name: 'Control de conexiones de lavarropas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Revisar canilla de paso (apertura/cierre), manguera de entrada (sin fisuras ni hinchazón), desagüe (sin obstrucciones) y nivel del equipo.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de termotanque eléctrico',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar estado de la resistencia eléctrica, ánodo de magnesio, válvula de seguridad T&P. Drenar sedimentos del fondo.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de lavavajillas',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar mangueras de entrada y salida, filtro del fondo, brazo aspersor, juntas de la puerta. Limpiar con ciclo vacío y vinagre.',
        priority: 'LOW',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 15,
        defaultSector: 'KITCHEN',
      },
    ],
  },
  {
    name: 'Gas Envasado (GLP)',
    icon: '🔶',
    description: 'Mantenimiento de instalaciones de gas envasado en garrafa o granel',
    displayOrder: 14,
    tasks: [
      {
        name: 'Inspección de regulador de presión de GLP',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar estado del regulador: fecha de vencimiento (5 años), ausencia de pérdidas (agua jabonosa), presión de salida correcta.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de válvulas y conexiones flexibles GLP',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de mangueras flexibles (fecha de vencimiento, sin grietas ni torceduras), abrazaderas y válvulas de corte. Norma NAG-200.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Verificación de ubicación y ventilación del tanque GLP',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Asegurar que el tanque de GLP esté en exterior ventilado, alejado de fuentes de calor y desagües. Verificar base/soporte y accesibilidad.',
        priority: 'HIGH',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 10,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Prueba de hermeticidad de instalación GLP',
        taskType: 'TEST',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Prueba con agua jabonosa o manómetro en toda la instalación de GLP. Obligatoria tras cualquier modificación.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Agua de Pozo',
    icon: '🚰',
    description: 'Mantenimiento de perforaciones y sistemas de agua de pozo',
    displayOrder: 15,
    tasks: [
      {
        name: 'Análisis fisicoquímico y bacteriológico de agua',
        taskType: 'TEST',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Tomar muestra y enviar a laboratorio. Verificar potabilidad: arsénico (común en llanura pampeana), nitratos, coliformes, dureza. Código Alimentario Argentino.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Service de bomba sumergible',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar caudal, presión, consumo eléctrico, estado de cables. Limpiar filtro de pie. Medir nivel estático y dinámico del pozo.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de brocal y sellado de perforación',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar que el brocal (cabezal del pozo) esté sellado para evitar contaminación superficial. Verificar que no haya fuentes contaminantes cercanas.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Mantenimiento de equipo de tratamiento de agua',
        taskType: 'ADJUSTMENT',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar filtros, resinas de ablandador, lámpara UV, ósmosis inversa. Reemplazar consumibles según indicación del fabricante.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Energía Solar y Sustentable',
    icon: '☀️',
    description: 'Mantenimiento de paneles solares, termotanque solar y sistemas sustentables',
    displayOrder: 16,
    tasks: [
      {
        name: 'Limpieza de paneles solares fotovoltaicos',
        taskType: 'CLEANING',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Limpiar con agua desmineralizada y paño suave. El polvo, hojas y excrementos de pájaros reducen rendimiento hasta 25%. Verificar sombras nuevas.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 30,
        defaultSector: 'ROOF',
      },
      {
        name: 'Inspección de sistema fotovoltaico completo',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar inversor (indicadores, ventilación), conexiones (corrosión, ajuste), cableado, estructura de soporte (oxidación, fijación al techo). Medir rendimiento vs esperado.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'ROOF',
      },
      {
        name: 'Control de termotanque solar',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar estado de colectores (vidrio, absorsor), tanque acumulador (ánodo, válvulas), cañerías y anticongelante (si usa glicol). Limpiar colectores.',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'ROOF',
      },
      {
        name: 'Verificación de sistema de recolección de agua de lluvia',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Limpiar filtros, verificar estado de tanque de almacenamiento, bomba, first-flush diverter. Controlar calidad del agua almacenada.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 20,
        defaultSector: 'GARDEN',
      },
      {
        name: 'Inspección de sistema de reciclado de aguas grises',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar filtros, bomba, calidad del agua tratada, estado de cañerías diferenciadas (color violeta según normativa).',
        priority: 'MEDIUM',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Domótica y Electrónica',
    icon: '📡',
    description: 'Mantenimiento de alarmas, cámaras, porteros y automatización',
    displayOrder: 17,
    tasks: [
      {
        name: 'Control de sistema de alarma',
        taskType: 'TEST',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar funcionamiento de todos los sensores (apertura, movimiento, rotura de vidrio), sirena, batería de respaldo, comunicación con monitoreo.',
        priority: 'HIGH',
        recurrenceType: 'MONTHLY',
        recurrenceMonths: 1,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Inspección de cámaras de seguridad',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar imagen de cada cámara, grabación, almacenamiento (disco/nube), estado de cableado, limpieza de lente, visión nocturna.',
        priority: 'MEDIUM',
        recurrenceType: 'QUARTERLY',
        recurrenceMonths: 3,
        estimatedDurationMinutes: 20,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Mantenimiento de portero eléctrico o videoportero',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar audio, video (si tiene), apertura eléctrica de puerta, cableado. Limpiar contactos de la botonera exterior.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'INSTALLATIONS',
      },
      {
        name: 'Control de automatización del hogar',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar funcionamiento de luces automáticas, cortinas motorizadas, termostatos inteligentes, hub central. Actualizar firmware. Verificar batería de sensores inalámbricos.',
        priority: 'LOW',
        recurrenceType: 'BIANNUAL',
        recurrenceMonths: 6,
        estimatedDurationMinutes: 30,
        defaultSector: 'INSTALLATIONS',
      },
    ],
  },
  {
    name: 'Cielorraso y Entrepisos',
    icon: '🏛',
    description: 'Mantenimiento de cielorrasos, entrepisos y entretechos',
    displayOrder: 18,
    tasks: [
      {
        name: 'Inspección de cielorraso suspendido (durlock/yeso)',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar fisuras en juntas, desprendimientos, manchas de humedad (indica filtración desde arriba), pandeo. Común en construcción argentina moderna.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de cielorraso de machimbre',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de la madera: deformaciones, hongos, termitas, fijación de tablas. Aplicar protector si corresponde.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Inspección de entretecho',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Acceder al espacio entre techo y cielorraso: verificar estado de estructura (cabriadas/tirantería), aislación térmica, presencia de plagas (murciélagos, avispas), cañerías.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'ROOF',
      },
      {
        name: 'Control de entrepiso de madera',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_RECOMMENDED',
        technicalDescription:
          'Verificar estado de vigas, machimbre o tablero inferior, crujidos excesivos, flexión. Buscar signos de termitas o pudrición.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
    ],
  },
  {
    name: 'Protección contra Rayos',
    icon: '🌩',
    description: 'Pararrayos y protección contra descargas atmosféricas',
    displayOrder: 19,
    tasks: [
      {
        name: 'Inspección de pararrayos',
        taskType: 'INSPECTION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar estado del captor, cable de bajada, puesta a tierra, conexiones. Medir resistencia de puesta a tierra dedicada (<10 ohms). Norma IRAM 2184.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 45,
        defaultSector: 'ROOF',
      },
      {
        name: 'Control post-tormenta eléctrica',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Tras tormenta eléctrica severa: verificar funcionamiento de artefactos electrónicos, disyuntor diferencial, dispositivos de protección contra sobretensiones (DPS).',
        priority: 'HIGH',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'ROOF',
      },
      {
        name: 'Verificación de equipotencialización',
        taskType: 'MEASUREMENT',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar que cañerías metálicas, estructuras metálicas, puesta a tierra y pararrayos estén vinculados al mismo sistema de puesta a tierra. Norma AEA 90364.',
        priority: 'HIGH',
        recurrenceType: 'CUSTOM',
        recurrenceMonths: 36,
        estimatedDurationMinutes: 45,
        defaultSector: 'ROOF',
      },
    ],
  },
  {
    name: 'Escaleras y Barandas',
    icon: '🪜',
    description: 'Mantenimiento de escaleras, barandas y accesos a terraza',
    displayOrder: 20,
    tasks: [
      {
        name: 'Inspección de escalera interior y exterior',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar estado de escalones (fisuras, desprendimientos, antideslizante), estructura, iluminación. En escaleras exteriores: verificar pendiente de escurrimiento.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 20,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Control de barandas y pasamanos',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar fijación firme (no deben tener juego), altura mínima (0.90m interior, 1.00m exterior según código de edificación), estado de soldaduras o fijaciones.',
        priority: 'HIGH',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Mantenimiento de escalera de acceso a terraza',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar fijación a muro, estado de peldaños, oxidación. Agregar antideslizante si no tiene. Aplica a escaleras marineras o de gato.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 15,
        defaultSector: 'TERRACE',
      },
    ],
  },
  {
    name: 'Documentación y Normativa',
    icon: '📋',
    description: 'Gestión de certificados, habilitaciones y documentación de la vivienda',
    displayOrder: 21,
    tasks: [
      {
        name: 'Renovación de certificado de gas (oblea)',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Tramitar renovación de la oblea de gas ante la distribuidora. Requiere inspección por gasista matriculado. Obligatorio según NAG-200/226.',
        priority: 'URGENT',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 24,
        estimatedDurationMinutes: 90,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Actualización de planos de instalaciones',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Mantener planos actualizados de instalación eléctrica, sanitaria y gas ante cualquier modificación. Requerido por código de edificación para trámites municipales.',
        priority: 'MEDIUM',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 120,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Revisión de póliza de seguro del hogar',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Verificar cobertura vigente, actualización de suma asegurada (por inflación), cobertura de eventos climáticos (granizo, inundación), responsabilidad civil.',
        priority: 'MEDIUM',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Verificación de habilitación municipal',
        taskType: 'EVALUATION',
        professionalRequirement: 'PROFESSIONAL_REQUIRED',
        technicalDescription:
          'Verificar que ampliaciones o modificaciones cuenten con permiso de obra municipal. Las obras sin habilitación afectan la cobertura del seguro y el valor de la propiedad.',
        priority: 'MEDIUM',
        recurrenceType: 'ON_DETECTION',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 60,
        defaultSector: 'INTERIOR',
      },
      {
        name: 'Archivo de comprobantes de mantenimiento',
        taskType: 'INSPECTION',
        professionalRequirement: 'OWNER_CAN_DO',
        technicalDescription:
          'Archivar facturas, certificados y registros fotográficos de todos los mantenimientos realizados. Útil para seguro, venta y seguimiento histórico.',
        priority: 'LOW',
        recurrenceType: 'ANNUAL',
        recurrenceMonths: 12,
        estimatedDurationMinutes: 30,
        defaultSector: 'INTERIOR',
      },
    ],
  },
];
